---
- name: Configure ElasticSearch APT key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Configure the ElasticSearch APT repositories
  apt_repository: repo="deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main"
                  state=present

- name: Install ElasticSearch
  apt: pkg=elasticsearch={{ elasticsearch_version }} state=present

- name: Configure ElasticSearch
  template: src=elasticsearch.yml.j2
            dest=/etc/elasticsearch/elasticsearch.yml
  notify:
    - Restart ElasticSearch

- name: Enable ElasticSearch service
  service: name=elasticsearch enabled=yes state=started

- name: Install ElasticSearch Cloud Plugin
  command: bin/plugin install elasticsearch/elasticsearch-cloud-aws/{{ elasticsearch_cloud_aws_plugin_version }}
           chdir=/usr/share/elasticsearch
           creates=/usr/share/elasticsearch/plugins/cloud-aws/elasticsearch-cloud-aws-{{ elasticsearch_cloud_aws_plugin_version }}.jar
  when: elasticsearch_cloud_aws_plugin_install
